### ISSUE TITLE
Downloaded videos are all of 0 size

### ISSUE THREAD

**Issue by matthuszagh** [amkhrjee/ocwd#4]
I tried to download the course at [https://ocw.mit.edu/courses/res-6-007-signals-and-systems-spring-2011/](https://ocw.mit.edu/courses/res-6-007-signals-and-systems-spring-2011/). When I do this, although all the video files are present in "LVideos", they don't have any content (are all of 0 size). By removing the `-q` flag from the `wget` invocation, I found that this script was attempting to download the videos from `https://ocw.mit.edu//www.archive.org/....`, but they are not available there. However, if you remove the `baseLink` and leading `//`, the download worked. The hackish way I did this, just to get it to work, was with `wget -q -O "./$2/$filename$index$extension" "${url:2:1000}"`.

**Comment by amkhrjee** [comment]
Thanks for creating the issue. These scripts rarely get tested by me as I made them as a one-time thing back when I was taking a few CS courses last year. And since the links are subject to change by MIT, these scripts are inherently unstable by nature.

I'll look into this and try to push a fix asap.

**Comment by amkhrjee** [comment]
This has been fixed with this commit: [6b094a2](https://github.com/amkhrjee/ocwd/commit/6b094a2103f051d4fc10fd6229fa58a8440e6903)
